### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by curtissmith** [sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation#1]
The link to "[openconfig/gnoi](https://github.com/openconfig/gnoi/blob/master/factory_reset/%E2%80%8B)" in the sentence "The factory reset API as described at [openconfig/gnoi](https://github.com/openconfig/gnoi/blob/master/factory_reset/%E2%80%8B) with tooling from [google/gnxi](https://github.com/google/gnxi/tree/master/gnoi_reset)." on page https://github.com/sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation/blob/main/gNOI_reset_proto.md is broken.

**Comment by sdeweese** [comment]
Fixed!
