### ISSUE TITLE
Link to Cisco internal document

### ISSUE THREAD

**Issue by curtissmith** [sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation#3]
Under the section heading "Learn more about YANG Suite" at https://github.com/sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation/blob/main/YANG_Suite.md there is a link to Cisco internal SalesConnect document [YANG Suite TDM](https://salesconnect.cisco.com/#/content-detail/8cc604e2-8903-4164-a4c4-24007b5d9735).

**Comment by sdeweese** [comment]
Modified resources
