### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by curtissmith** [sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation#4]
Under section heading "Retrieve run config formatted with JSON for RESTCONF" at https://github.com/sdeweese/CLUS22-LTROPS-1836-programmabilty-and-automation/blob/main/Terraform.md there seem to be missing steps as the section trails off without executing anything.  The contents of acl.tf need to be included in a manner than can be copy and pasted into the text editor.  How will acl.tf be used?

**Comment by sdeweese** [comment]
Great questions--I've updated the TF file
